[example-1]
input_data = "FBFBBFFRLR"
answer_a = "357"

[example-2]
input_data = "BFFFBBFRRR"
answer_a = "567"

[example-3]
input_data = "FFFBBBFRRR"
answer_a = "119"

[example-4]
input_data = "BBFFBBFRLL"
answer_a = "820"
